[package]
name = "graphembed"
version = "0.0.1"
authors = ["jeanpierre.both@gmail.com"]
#repository = "https://gitlab.com/jpboth/archaea"
keywords = ["graph", "embedding", "hash"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "graph embedding"


[features]





[lib]

path = "src/lib.rs"


[dependencies]
# default is version spec is ^ meaning can update up to max non null version number
# cargo doc --no-deps avoid dependencies doc generation
#
petgraph = {version = "0.6"}

serde= {version = "1.0", features = ["derive"] }
serde_json= {version = "1.0"}

num = {version = "0.4"}
num-traits = {version = "0.2"}

# linear algebra stuff
ndarray = {version = "0.15", features=["rayon", "serde"]}
ndarray-linalg = {version = "0.14", features = ["intel-mkl-static"]}
lax = {version = "0.2"}
lapacke = {version = "0.5"}
sprs = {version = "0.11"}

# io

csv = {version = "1.1.6"}


# for //
crossbeam-utils = {version = "0.8"}
crossbeam-channel = {version = "0.5"}
parking_lot = {version="0.11"}
rayon = {version = "1.5"}
num_cpus = {version = "1.13.0"}

cpu-time = {version = "1.0"}
clap = {version = "2.33"}

##
ahash = {version = "0.7"}
probminhash = {version = "0.1.5"}

annembed ={ path = "../annembed"}

#  
lazy_static = { version = "1.4"}

# decreasing order of log for debug build : (max_level_)trace debug info warn error off
# decreasing order of log for release build (release_max_level_)  .. idem
#log = { version = "0.4", features = ["max_level_trace", "release_max_level_trace"] }
log = { version = "0.4"}
env_logger = { version = "0.9"}
anyhow = {version = "1.0"}

# for documentation
katexit = {version = "0.1.0"}
